# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.2 on 2016-02-15 09:46
=======
# Generated by Django 1.9 on 2016-01-28 07:12
>>>>>>> d23dacb8a9233a959712f93c9a77eb230e4fd3f5
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('usertype', models.CharField(max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('heading', models.CharField(max_length=90)),
                ('level', models.IntegerField()),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('genre', models.CharField(choices=[('', '---------'), ('1', 'politics'), ('2', 'sports'), ('3', 'science'), ('4', 'entertainment'), ('5', 'world'), ('6', 'nation'), ('7', 'environment'), ('8', 'businessandcommerce')], default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=50)),
                ('choice2', models.CharField(max_length=50)),
                ('choice3', models.CharField(max_length=50)),
                ('choice4', models.CharField(max_length=50)),
                ('right_choice', models.CharField(choices=[('', '---------'), (models.CharField(max_length=50), 'choice1'), (models.CharField(max_length=50), 'choice2'), (models.CharField(max_length=50), 'choice3'), (models.CharField(max_length=50), 'choice4')], default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
>>>>>>> d23dacb8a9233a959712f93c9a77eb230e4fd3f5
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=999)),
                ('time', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
=======
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.article')),
>>>>>>> d23dacb8a9233a959712f93c9a77eb230e4fd3f5
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('response', models.CharField(default='', max_length=2)),
                ('key', models.BooleanField(default=False)),
=======
>>>>>>> d23dacb8a9233a959712f93c9a77eb230e4fd3f5
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('', '---------'), ('1', 'vocabulary'), ('2', 'grammar'), ('3', 'comprehension')], max_length=2)),
<<<<<<< HEAD
                ('choice1', models.CharField(max_length=50)),
                ('choice2', models.CharField(max_length=50)),
                ('choice3', models.CharField(max_length=50)),
                ('choice4', models.CharField(max_length=50)),
                ('right_choice', models.CharField(choices=[('', '---------'), ('1', 'choice1'), ('2', 'choice2'), ('3', 'choice3'), ('4', 'choice4')], default='', max_length=2)),
=======
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.article')),
>>>>>>> d23dacb8a9233a959712f93c9a77eb230e4fd3f5
            ],
        ),
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_name', models.CharField(max_length=99)),
<<<<<<< HEAD
                ('word_meaning', models.CharField(max_length=99)),
=======
            ],
        ),
        migrations.CreateModel(
            name='word_meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_meaning', models.CharField(max_length=99)),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.word')),
>>>>>>> d23dacb8a9233a959712f93c9a77eb230e4fd3f5
            ],
        ),
        migrations.AddField(
            model_name='performance',
<<<<<<< HEAD
            name='question_id2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.question'),
        ),
        migrations.AddField(
            model_name='performance',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
=======
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.question'),
>>>>>>> d23dacb8a9233a959712f93c9a77eb230e4fd3f5
        ),
    ]
