# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='c:/Python27/desitomato/media/None')),
                ('heading', models.CharField(max_length=90)),
                ('level', models.IntegerField()),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('genre', models.CharField(choices=[('', '---------'), ('1', 'politics'), ('2', 'sports'), ('3', 'science'), ('4', 'entertainment'), ('5', 'world'), ('6', 'nation'), ('7', 'environment'), ('8', 'businessandcommerce')], default='', max_length=2)),
                ('parsed', models.BooleanField(default=False)),
            ],
        ),
    ]
