# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='question_id',
            new_name='question_id2',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='c:/Python27/desitomato/media/None'),
        ),
    ]
