# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='english.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='article_id',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='english.article'),
            preserve_default=False,
        ),
    ]
