# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_auto_20160202_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='right_choice',
            field=models.CharField(choices=[('', '---------'), ('1', 'choice1'), ('2', 'choice2'), ('3', 'choice3'), ('4', 'choice4')], default='', max_length=2),
        ),
    ]
