# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_auto_20160215_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='word',
            new_name='wordmeaning',
        ),
    ]
