# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_auto_20160215_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='fillblank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_choice', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='matchit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftcol1', models.CharField(max_length=30)),
                ('leftcol2', models.CharField(max_length=30)),
                ('leftcol3', models.CharField(max_length=30)),
                ('leftcol4', models.CharField(max_length=30)),
                ('rightcol1', models.CharField(max_length=30)),
                ('rightcol2', models.CharField(max_length=30)),
                ('rightcol3', models.CharField(max_length=30)),
                ('rightcol4', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='mcq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=30)),
                ('choice2', models.CharField(max_length=30)),
                ('choice3', models.CharField(max_length=30)),
                ('choice4', models.CharField(max_length=30)),
                ('right_choice', models.CharField(choices=[('', '---------'), ('1', 'choice1'), ('2', 'choice2'), ('3', 'choice3'), ('4', 'choice4')], default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='morethanonechoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=30)),
                ('choice2', models.CharField(max_length=30)),
                ('choice3', models.CharField(max_length=30)),
                ('choice4', models.CharField(max_length=30)),
                ('right_choice', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'choice1'), ('2', 'choice2'), ('3', 'choice3'), ('4', 'choice4')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='sample_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=30)),
                ('subtopic', models.CharField(choices=[('', '---------'), ('1', 'noun'), ('2', 'pronoun'), ('3', 'adjective'), ('4', 'adverb'), ('5', 'verb'), ('6', 'conjunction or interjection'), ('7', 'articels'), ('8', 'determiners')], default='', max_length=2)),
                ('level', models.CharField(choices=[('', '---------'), ('1', 'low'), ('2', 'medium'), ('3', 'high')], default='', max_length=2)),
                ('question_type', models.CharField(choices=[('', '---------'), ('1', 'multiple choice questions'), ('2', 'more than one correct choice'), ('3', 'true or false'), ('4', 'fill in the blanks'), ('5', 'edit the sentence'), ('6', 'match the following')], default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='truefalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_choice', models.CharField(choices=[('', '---------'), ('1', 'true'), ('2', 'false')], default='', max_length=2)),
                ('sample_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.sample_question')),
            ],
        ),
        migrations.AddField(
            model_name='morethanonechoice',
            name='sample_question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.sample_question'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='sample_question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.sample_question'),
        ),
        migrations.AddField(
            model_name='matchit',
            name='sample_question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.sample_question'),
        ),
        migrations.AddField(
            model_name='fillblank',
            name='sample_question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.sample_question'),
        ),
    ]
