# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_auto_20160202_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='performance',
            name='response',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='performance',
            name='user_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
