# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_auto_20160203_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='response',
            new_name='response3',
        ),
    ]
