# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_auto_20160224_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample_performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun_score', models.CharField(max_length=9)),
                ('pronoun_score', models.CharField(max_length=9)),
                ('adjective_score', models.CharField(max_length=9)),
                ('adverb_score', models.CharField(max_length=9)),
                ('verb_score', models.CharField(max_length=9)),
                ('conjunction_score', models.CharField(max_length=9)),
                ('article_score', models.CharField(max_length=9)),
                ('determiner_score', models.CharField(max_length=9)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
