# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0006_sample_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='theory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('short_summary', models.CharField(max_length=200)),
                ('long_description', models.CharField(max_length=999)),
                ('example', models.CharField(max_length=500)),
                ('is_subtopic', models.CharField(choices=[('', '---------'), ('noun', 'noun'), ('pronoun', 'pronoun'), ('adjective', 'adjective'), ('adverb', 'adverb'), ('verb', 'verb'), ('conjunctionandinterjection', 'conjunction or interjection'), ('articels', 'articels'), ('determiners', 'determiners'), ('no', 'no')], default='', max_length=20)),
            ],
        ),
    ]
