# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0006_auto_20160207_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='response3',
            new_name='response',
        ),
    ]
