# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 18:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0007_theory'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_visited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.article')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='topic_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun_score', models.CharField(max_length=9)),
                ('pronoun_score', models.CharField(max_length=9)),
                ('adjective_score', models.CharField(max_length=9)),
                ('adverb_score', models.CharField(max_length=9)),
                ('verb_score', models.CharField(max_length=9)),
                ('conjunction_score', models.CharField(max_length=9)),
                ('article_score', models.CharField(max_length=9)),
                ('determiner_score', models.CharField(max_length=9)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sample_performance',
            name='adjective_score',
        ),
        migrations.RemoveField(
            model_name='sample_performance',
            name='adverb_score',
        ),
        migrations.RemoveField(
            model_name='sample_performance',
            name='article_score',
        ),
        migrations.RemoveField(
            model_name='sample_performance',
            name='conjunction_score',
        ),
        migrations.RemoveField(
            model_name='sample_performance',
            name='determiner_score',
        ),
        migrations.RemoveField(
            model_name='sample_performance',
            name='noun_score',
        ),
        migrations.RemoveField(
            model_name='sample_performance',
            name='pronoun_score',
        ),
        migrations.RemoveField(
            model_name='sample_performance',
            name='verb_score',
        ),
        migrations.AddField(
            model_name='sample_performance',
            name='response',
            field=models.CharField(default=3, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample_performance',
            name='sample_question_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='english.sample_question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample_question',
            name='article_id',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='english.article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample_question',
            name='question_type',
            field=models.CharField(max_length=2),
        ),
    ]
