# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0008_auto_20160316_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_question',
            name='question_type_type',
            field=models.CharField(choices=[('1', 'manual'), ('2', 'generated')], default='3', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample_question',
            name='question_type',
            field=models.CharField(choices=[('', '---------'), ('1', 'multiple choice questions'), ('2', 'more than one correct choice'), ('3', 'true or false'), ('4', 'fill in the blanks'), ('5', 'edit the sentence'), ('6', 'match the following')], default='', max_length=2),
        ),
    ]
