# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0009_auto_20160317_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='verb_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_form', models.CharField(max_length=20)),
                ('second_form', models.CharField(max_length=20)),
                ('third_form', models.CharField(max_length=20)),
                ('plural_form', models.CharField(max_length=20)),
                ('ing_form', models.CharField(max_length=20)),
            ],
        ),
    ]
