# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0011_common_words'),
    ]

    operations = [
        migrations.DeleteModel(
            name='common_words',
        ),
    ]
