# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0012_delete_common_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='common_words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
            ],
        ),
    ]
