# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0013_common_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='common_words',
            old_name='word',
            new_name='word_anurag',
        ),
    ]
