# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0014_auto_20160322_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('word_meaning', models.CharField(max_length=500)),
                ('word_tag', models.CharField(choices=[('', '---------'), ('n', 'noun'), ('a', 'adjective'), ('r', 'adverb'), ('v', 'verb')], default='', max_length=20)),
                ('example1', models.CharField(max_length=300)),
                ('example2', models.CharField(max_length=300)),
                ('example3', models.CharField(max_length=300)),
            ],
        ),
    ]
