# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0016_adjective_form_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='synonyms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym_def', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='example1',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='example2',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='example3',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='word_tag',
        ),
        migrations.AddField(
            model_name='synonyms',
            name='word_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.dictionary'),
        ),
    ]
