# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0017_auto_20160402_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='antonyms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antonym_def', models.CharField(max_length=40)),
                ('tag', models.CharField(choices=[('', '---------'), ('a', 'adjective'), ('s', 'adverb'), ('v', 'verb'), ('n', 'noun')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='relateds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_def', models.CharField(max_length=40)),
                ('tag', models.CharField(choices=[('', '---------'), ('a', 'adjective'), ('s', 'adverb'), ('v', 'verb'), ('n', 'noun')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='similars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_def', models.CharField(max_length=40)),
                ('tag', models.CharField(choices=[('', '---------'), ('a', 'adjective'), ('s', 'adverb'), ('v', 'verb'), ('n', 'noun')], default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='synonyms',
            name='tag',
            field=models.CharField(choices=[('', '---------'), ('a', 'adjective'), ('s', 'adverb'), ('v', 'verb'), ('n', 'noun')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='word_meaning',
            field=models.CharField(max_length=5000),
        ),
        migrations.AddField(
            model_name='similars',
            name='word_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.dictionary'),
        ),
        migrations.AddField(
            model_name='relateds',
            name='word_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.dictionary'),
        ),
        migrations.AddField(
            model_name='antonyms',
            name='word_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.dictionary'),
        ),
    ]
