# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0018_auto_20160403_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='essay_attempted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_content', models.CharField(max_length=2000)),
                ('essay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.essay')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_essay_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter1', models.IntegerField()),
                ('parameter1_text', models.CharField(max_length=300)),
                ('parameter2', models.IntegerField()),
                ('parameter2_text', models.CharField(max_length=300)),
                ('parameter3', models.IntegerField()),
                ('parameter3_text', models.CharField(max_length=300)),
                ('parameter4_text', models.CharField(max_length=300)),
                ('parameter4', models.IntegerField()),
                ('parameter5_text', models.CharField(max_length=300)),
                ('essay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.essay')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
