# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0019_essay_essay_attempted_user_essay_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_question',
            name='question_text',
            field=models.CharField(max_length=300),
        ),
    ]
