# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0020_auto_20160411_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_question',
            name='paragraph_pos',
            field=models.IntegerField(default='3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample_question',
            name='sentence_pos',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
