# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0021_auto_20160411_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_question',
            name='tag',
            field=models.BooleanField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample_question',
            name='word',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
