# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0023_auto_20160413_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='c:/pythondata/desitomato/media/None'),
        ),
    ]
