# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0024_auto_20160416_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='word',
            field=models.CharField(max_length=50),
        ),
    ]
