# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0025_auto_20160420_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='word_meaning',
            field=models.CharField(default='h', max_length=3000),
            preserve_default=False,
        ),
    ]
