# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0026_bookmark_word_meaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='list1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_name', models.CharField(max_length=50)),
                ('word_meaning', models.CharField(max_length=2000)),
                ('word_example', models.CharField(max_length=4000)),
            ],
        ),
    ]
