# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0027_list1'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_performance',
            name='article_under',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='english.article'),
            preserve_default=False,
        ),
    ]
