# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0028_sample_performance_article_under'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_performance',
            name='paragraph_pos',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample_performance',
            name='sentence_pos',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample_performance',
            name='word',
            field=models.CharField(blank=True, max_length=301),
        ),
    ]
