# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0029_auto_20160429_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('', '---------'), ('1', 'grammar'), ('2', 'comprehension')], default='', max_length=2),
        ),
    ]
