# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0031_auto_20160516_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_question',
            name='subtopic',
            field=models.CharField(choices=[('', '---------'), ('1', 'noun'), ('2', 'pronoun'), ('3', 'adjective'), ('4', 'adverb'), ('5', 'verb'), ('6', 'conjunction or interjection'), ('7', 'articels'), ('8', 'determiners'), ('9', 'vocabulary')], default='', max_length=2),
        ),
    ]
